# Generated by Django 4.2.1 on 2023-05-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('company', models.TextField(db_index=True, max_length=150)),
                ('kitchen', models.TextField(db_index=True, max_length=150)),
                ('time', models.TextField(db_index=True, max_length=150)),
                ('cost', models.TextField(db_index=True, max_length=150)),
                ('feature', models.TextField(blank=True, db_index=True)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('imageM', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='compon.tag')),
            ],
        ),
    ]
