# Generated by Django 4.2.1 on 2023-05-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comp',
            old_name='company',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comp',
            old_name='cost',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='imageM',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='time',
        ),
    ]
