# Generated by Django 4.2.1 on 2023-05-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compon', '0002_rename_company_comp_name_rename_cost_comp_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='halal',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
